name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.war

  deploy:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          
      - name: Copy jar file
        uses: ArthurYdalgo/github-action-scp@release
        with:
          local: "*.war"
          remote: /home/ubuntu
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey : ${{ secrets.PRIVATE_KEY }}

