name: Example CI

on:
  push:
    branches:
      - '**'   # Trigger on all branches (can be modified to specific branches)
  pull_request:
    branches:
      - '**'   # Trigger on all pull requests (can be modified)

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # Condition to run job only on the main branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This job runs only on the 'main' branch"

  job_on_feature:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature')  # Condition to run job only on the 'feature' branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This job runs only on the 'feature' branch"
