name: Java CI with Maven

# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK 11 (You can choose a different version if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # You can choose another distribution if needed

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Run tests (optional step if you want to ensure the tests run)
      - name: Run tests
        run: mvn test

      # (Optional) Publish the build or deploy the project here
